import "./index.html";
import "./libs/amenu/amenu.css";
import "./css/style.css";
import "./libs/amenu/amenu.js";
import "./scripts/scroll.js";
import "./scripts/tabs.js";
import "./scripts/accordeon.js";
import "./scripts/getData.js";
import "./scripts/sendForm.js";